# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Wait for Tomcat to start
      run: sleep 20

    - name: Check for 404 errors
      run: |
        RESPONSE=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8080/your-app)
        if [ "$RESPONSE" -ne 200 ]; then
          echo "Error: Received $RESPONSE from the application"
          exit 1
        else
          echo "Application started successfully with response code $RESPONSE"
        fi
