name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y ant

    - name: Run Ant build
      run: ant -f build.xml

    - name: Wait for Tomcat to start
      run: sleep 20

    - name: Check for 404 errors
      run: |
        RESPONSE=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8080/your-app)
        if [ "$RESPONSE" -ne 200 ]; then
          echo "Error: Received $RESPONSE from the application"
          exit 1
        else
          echo "Application started successfully with response code $RESPONSE"
        fi
